services:
  web:
    image: node:22.14
    platform: linux/x86_64
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    # env_file:
    #   - .env
    ports:
      - 3000:3000
    command: bash -c "npm i && npm run dev"
